#! perl

# $Id: /local/languages/jako/t/harness 12378 2006-04-19T18:02:12.737142Z bernhard  $

=head1 NAME

languages/jako/t/harness - A harness for Jako 

=head1 SYNOPSIS

  cd languages && perl -I../lib jako/t/harness --files

=head1 DESCRIPTION

If I'm called with a single
argument of "--files", I just return a list of files to process.
This list is one per line, and is relative to the languages dir.

=cut

use Parrot::Test::Harness language => 'jako';
