#!perl
# Copyright (C) 2005, The Perl Foundation.
# $Id: /parrotcode/trunk/t/compilers/tge/harness 470 2006-12-05T03:30:45.414067Z svm  $

use strict;
use warnings;
use Test::Harness;
use File::Spec;


my @files;

# Per Leo on 18APR2005, run the test suite with --gc-debug

if ($ENV{TEST_PROG_ARGS} && $ENV{TEST_PROG_ARGS} !~ /\b--gc-debug\b/) {
  $ENV{TEST_PROG_ARGS} .= " --gc-debug"; 
}

if (@ARGV) {
    # Someone specified tests for me to run.
    @files = grep {-f $_} @ARGV
} else {
    # Called with no args, run the full suite.
    @files = glob( File::Spec->catfile( "t", "*.t" ) );
}

exit unless @files;
runtests(@files);
