#! perl

# $Id: /parrotcode/local/languages/abc/t/harness 1801 2007-02-15T06:52:47.129138Z chromatic  $

use FindBin;
use lib qw( . lib ../lib ../../lib ../../lib );
use Parrot::Test::Harness language => 'abc', compiler => 'abc.pbc';
