#! perl

# $Id: /parrotcode/trunk/languages/pynie/t/harness 2169 2007-03-09T09:00:39.006560Z paultcochrane  $

use FindBin;
use lib qw( . lib ../lib ../../lib ../../lib );
use Parrot::Test::Harness language => 'pynie', compiler => 'pynie.pbc';

# Set up PERL6LIB environment path so the "use" tests can find libraries
# $ENV{PERL6LIB} = "$Bin/01-sanity";
