#! perl

# $Id: harness 37359 2009-03-12 19:44:02Z fperrad $

# pragmata
use strict;
use warnings;
use 5.008;

use lib qw( . lib ../lib ../../lib ../../../lib );

use Parrot::Test::Harness language => 'abc',
                          compiler => 'abc.pbc';
