#! perl

# $Id: harness 43593 2010-01-26 02:39:50Z jkeenan $

use FindBin;
use lib qw( . lib ../lib ../../lib ../../../lib );
use Parrot::Test::Harness
    language  => 'nqp',
    exec      => [ './parrot', 'compilers/nqp/nqp.pbc' ],
    files     => [ 'compilers/nqp/t/*.t' ];

    #arguments => [ '--files' ],
    #verbosity => 1,
