#! perl -w
# $Id: /parrotcode/trunk/languages/scheme/schemec 470 2006-12-05T03:30:45.414067Z svm  $

use strict;
use lib 'languages/scheme';
use Scheme;

sub Usage {
  print <<_EOF_;
usage: $0 <file.scheme>
_EOF_
  exit;
}

defined $ARGV[0] or Usage();
$ARGV[0] =~ m/\.scheme$|\.scm$/i or Usage();

print Scheme->new($ARGV[0])->compile();
