#! perl -w
# $Id: /local/languages/scheme/schemec 11501 2006-02-10T18:27:13.457666Z particle  $

use strict;
use lib 'languages/scheme';
use Scheme;

sub Usage {
  print <<_EOF_;
usage: $0 <file.scheme>
_EOF_
  exit;
}

defined $ARGV[0] or Usage();
$ARGV[0] =~ m/\.scheme$|\.scm$/i or Usage();

print Scheme->new($ARGV[0])->compile();
