#!/usr/bin/perl

# $Id: /parrotcode/trunk/languages/cardinal/t/harness 470 2006-12-05T03:30:45.414067Z svm  $

use FindBin;
use lib qw( . lib ../lib ../../lib ../../lib );
use Parrot::Test::Harness language => 'Cardinal';

