#! perl

# $Id: harness 15656 2006-11-18 15:43:01Z pmichaud $

use FindBin;
use lib qw( . lib ../lib ../../lib ../../lib );
use Parrot::Test::Harness language => 'perl6', compiler => 'perl6.pbc';

# Set up PERL6LIB environment path so the "use" tests can find libraries
$ENV{PERL6LIB} = "$Bin/01-sanity";
