#! perl

# $Id: /local/languages/perl6/t/harness 13278 2006-07-13T13:40:14.092490Z coke  $

use FindBin;
use lib qw( . lib ../lib ../../lib ../../lib );
use Parrot::Test::Harness language => 'perl6', compiler => 'perl6.pbc';

# Set up PERL6LIB environment path so the "use" tests can find libraries
$ENV{PERL6LIB} = "$Bin/01-sanity";
