#! perl

# $Id: /parrotcode/trunk/languages/perl6/t/harness 470 2006-12-05T03:30:45.414067Z svm  $

use FindBin;
use lib qw( . lib ../lib ../../lib ../../lib );
use Parrot::Test::Harness language => 'perl6', compiler => 'perl6.pbc';

# Set up PERL6LIB environment path so the "use" tests can find libraries
$ENV{PERL6LIB} = "$Bin/01-sanity";
