#! perl

# $Id: /parrotcode/local/languages/regex/t/harness 2657 2007-03-31T01:57:48.733769Z chromatic  $

use FindBin;
use lib qw( . lib ../lib ../../lib ../../lib );

use Parrot::Test::Harness language => 'regex';
