#! perl

# $Id: /parrotcode/local/languages/PIR/t/harness 2657 2007-03-31T01:57:48.733769Z chromatic  $

# language is the directory where the language implementation lives
# See perldoc Parrot::Test::Harness for details

use Parrot::Test::Harness language => 'PIR';
