#! perl

# $Id: harness 17306 2007-03-03 10:59:02Z bernhard $

# language is the directory where the language implementation lives
# See perldoc Parrot::Test::Harness for details

use Parrot::Test::Harness language => 'PIR';
