#! perl

# $Id: harness 27031 2008-04-19 12:17:01Z bernhard $

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../../../lib";

use Parrot::Test::Harness
    language => 'nqp',
    exec     => [ '../../../parrot', 'nqp.pbc' ],
    files    => [ '../t/*.t' ];
